// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8yIln3qm-fg41Cd0ANp6Fev-INj7bvUc',
    appId: '1:844752506566:web:01bbe98a4c7c718fdad1c7',
    messagingSenderId: '844752506566',
    projectId: 'chatting-app-f92ba',
    authDomain: 'chatting-app-f92ba.firebaseapp.com',
    storageBucket: 'chatting-app-f92ba.appspot.com',
    measurementId: 'G-T874N5NNJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu9oWpikkDu2nFwp3ixidN2IvJKDm3SNM',
    appId: '1:844752506566:android:09e7e29a133dbfbfdad1c7',
    messagingSenderId: '844752506566',
    projectId: 'chatting-app-f92ba',
    storageBucket: 'chatting-app-f92ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhhubDXa7Ri1H4Rj3ulyC0epHdG8U0wg0',
    appId: '1:844752506566:ios:447add73a0f6476edad1c7',
    messagingSenderId: '844752506566',
    projectId: 'chatting-app-f92ba',
    storageBucket: 'chatting-app-f92ba.appspot.com',
    iosBundleId: 'com.example.chatAppWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8yIln3qm-fg41Cd0ANp6Fev-INj7bvUc',
    appId: '1:844752506566:web:701ca6895111d053dad1c7',
    messagingSenderId: '844752506566',
    projectId: 'chatting-app-f92ba',
    authDomain: 'chatting-app-f92ba.firebaseapp.com',
    storageBucket: 'chatting-app-f92ba.appspot.com',
    measurementId: 'G-21Y4N613BZ',
  );
}
